### ISSUE TITLE
Error on maya launch OpenPype 3.15.1

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#340]
In GitLab by @support-bot on Mar 8, 2023, 13:11

> From...

## Log

```
# openpype.hosts.maya : Running callback on init..
# AbcImport v1.0 using Alembic 1.8.3 (built Nov  2 2022 10:43:12)
# AbcExport v1.0 using Alembic 1.8.3 (built Nov  2 2022 10:43:12)
file -f -new;
# openpype.hosts.maya : Running callback on new..
# Warning: EventCallback : Failed to execute event callback < EventCallback - on_new > /prod/softprod/apps/openpype/python39-ci-with-docker/linux/openpype/hosts/maya/api/pipeline.py
# Traceback (most recent call last):
#   File "/prod/softprod/apps/openpype/python39-ci-with-docker/linux/openpype/lib/events.py", line 195, in process_event
#     callback()
#   File "/prod/softprod/apps/openpype/python39-ci-with-docker/linux/openpype/hosts/maya/api/pipeline.py", line 630, in on_new
#     lib.set_context_settings()
#   File "/prod/softprod/apps/openpype/python39-ci-with-docker/linux/openpype/hosts/maya/api/lib.py", line 2123, in set_context_settings
#     set_scene_fps(fps)
#   File "/prod/softprod/apps/openpype/python39-ci-with-docker/linux/openpype/hosts/maya/api/lib.py", line 2003, in set_scene_fps
#     raise ValueError("Unsupported FPS value: `%s`" % fps)
# ValueError: Unsupported FPS value: `25.0`
// untitled
commandPort -securityWarning -name commandportDefault;
onSetCurrentLayout "General";
# openpype.hosts.maya.api.customize : Installing override_component_mask_commands..
   adding renderSetup observer ...
// Warning: file: /users_roaming/osotimehin/maya/2023/prefs/filePathEditorRegistryPrefs.mel line 4: filePathEditor: Attribute 'aiImage.filename' is invalid or is not designated 'usedAsFilename'.
// Warning: file: /users_roaming/osotimehin/maya/2023/prefs/filePathEditorRegistryPrefs.mel line 5: filePathEditor: Attribute 'aiPhotometricLight.aiFilename' is invalid or is not designated 'usedAsFilename'.
// Warning: file: /users_roaming/osotimehin/maya/2023/prefs/filePathEditorRegistryPrefs.mel line 6: filePathEditor: Attribute 'aiStandIn.dso' is invalid or is not designated 'usedAsFilename'.
// Warning: file: /users_roaming/osotimehin/maya/2023/prefs/filePathEditorRegistryPrefs.mel line 7: filePathEditor: Attribute 'aiVolume.filename' is invalid or is not designated 'usedAsFilename'.
# scriptsmenu.launchformaya : Attempting to build menu ...
// Warning: file: /prod/softprod/apps/maya/2023.3/linux/scripts/others/supportRenderers.mel line 67: The renderer "arnold" used by this scene, is not currently available. The "mayaSoftware" renderer will be used instead. To prevent this message from being displayed in the future, set the environment variable: MAYA_NO_WARNING_FOR_MISSING_DEFAULT_RENDERER=1


```

## Softwares concerned

Maya, Fix

**Comment by OlivierOsotimehin** [comment]
this issues seams to be gone when testing on my rocky machine
