### ISSUE TITLE
Bug: error publishing task surface rendering in maya / arnold / openpype

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#417]
### Current Behavior:

Publish of a render failed (Publish - surface  646de537d7058b0640828daa ) 

### Expected Behavior:

Have .mov version on ftrack 

### Version

3.15.8-nightly.3

### What platform you are running OpenPype on?

Linux / Centos

### Steps To Reproduce:

Publish the asset cube in the surface task on the project **TEST_OP2_PUB_23_7**

### Relevant log output:

```shell
: STDOUT: ERROR - Traceback (most recent call last):
2023-05-24 12:26:57:  0: STDOUT:   File "/prod/softprod/apps/openpype/CENTOS/3.15/dependencies/pyblish/plugin.py", line 522, in __explicit_process
2023-05-24 12:26:57:  0: STDOUT:     runner(*args)
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_colorspace_data.py", line 46, in process
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/publish/publish_plugins.py", line 412, in set_representation_colorspace
2023-05-24 12:26:57:  0: STDOUT:     colorspace = colorspace or get_imageio_colorspace_from_filepath(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/colorspace.py", line 106, in get_imageio_colorspace_from_filepath
2023-05-24 12:26:57:  0: STDOUT:     file_match = re.search(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 201, in search
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 304, in _compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_compile.py", line 764, in compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 948, in parse
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 443, in _parse_sub
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 668, in _parse
2023-05-24 12:26:57:  0: STDOUT: re.error: nothing to repeat at position 0
2023-05-24 12:26:57:  0: STDOUT: Traceback (most recent call last):
2023-05-24 12:26:57:  0: STDOUT:   File "/prod/softprod/apps/openpype/CENTOS/3.15/dependencies/pyblish/plugin.py", line 522, in __explicit_process
2023-05-24 12:26:57:  0: STDOUT:     runner(*args)
2023-05-24 12:26:57:  0: STDOUT:   File "<string>", line 46, in process
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/publish/publish_plugins.py", line 412, in set_representation_colorspace
2023-05-24 12:26:57:  0: STDOUT:     colorspace = colorspace or get_imageio_colorspace_from_filepath(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/colorspace.py", line 106, in get_imageio_colorspace_from_filepath
2023-05-24 12:26:57:  0: STDOUT:     file_match = re.search(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 201, in search
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 304, in _compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_compile.py", line 764, in compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 948, in parse
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 443, in _parse_sub
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 668, in _parse
2023-05-24 12:26:57:  0: STDOUT: re.error: nothing to repeat at position 0
2023-05-24 12:26:57:  0: STDOUT: ERROR:pyblish.plugin:Traceback (most recent call last):
2023-05-24 12:26:57:  0: STDOUT:   File "/prod/softprod/apps/openpype/CENTOS/3.15/dependencies/pyblish/plugin.py", line 522, in __explicit_process
2023-05-24 12:26:57:  0: STDOUT:     runner(*args)
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_colorspace_data.py", line 46, in process
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/publish/publish_plugins.py", line 412, in set_representation_colorspace
2023-05-24 12:26:57:  0: STDOUT:     colorspace = colorspace or get_imageio_colorspace_from_filepath(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/colorspace.py", line 106, in get_imageio_colorspace_from_filepath
2023-05-24 12:26:57:  0: STDOUT:     file_match = re.search(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 201, in search
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 304, in _compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_compile.py", line 764, in compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 948, in parse
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 443, in _parse_sub
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 668, in _parse
2023-05-24 12:26:57:  0: STDOUT: re.error: nothing to repeat at position 0
2023-05-24 12:26:57:  0: STDOUT: Traceback (most recent call last):
2023-05-24 12:26:57:  0: STDOUT:   File "/prod/softprod/apps/openpype/CENTOS/3.15/dependencies/pyblish/plugin.py", line 522, in __explicit_process
2023-05-24 12:26:57:  0: STDOUT:     runner(*args)
2023-05-24 12:26:57:  0: STDOUT:   File "<string>", line 46, in process
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/publish/publish_plugins.py", line 412, in set_representation_colorspace
2023-05-24 12:26:57:  0: STDOUT:     colorspace = colorspace or get_imageio_colorspace_from_filepath(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/pipeline/colorspace.py", line 106, in get_imageio_colorspace_from_filepath
2023-05-24 12:26:57:  0: STDOUT:     file_match = re.search(
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 201, in search
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/re.py", line 304, in _compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_compile.py", line 764, in compile
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 948, in parse
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 443, in _parse_sub
2023-05-24 12:26:57:  0: STDOUT:   File "/users_roaming/chector/.pyenv/versions/3.9.6/lib/python3.9/sre_parse.py", line 668, in _parse
2023-05-24 12:26:57:  0: STDOUT: re.error: nothing to repeat at position 0
2023-05-24 12:26:57:  0: STDOUT: !!! ERR: 2023-05-24 12:26:57,132 >>> { CLI-publish }: [ Failed ExtractColorspaceData: nothing to repeat at position 0 -- ('/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_colorspace_data.py', 668, '_parse', '') ] 
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_hierarchy_avalon.py.ExtractHierarchyToAvalon'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_thumbnail_from_source.py.ExtractThumbnailFromSource'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_scanline_exr.py.ExtractScanlineExr'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_thumbnail.py.ExtractThumbnail'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_color_transcode.py.ExtractOIIOTranscode'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_review.py.ExtractReview'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_burnin.py.ExtractBurnin'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_review_slate.py.ExtractReviewSlate'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/extract_colorspace_data.py.ExtractColorspaceData'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate_subset_group.py.IntegrateSubsetGroup'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/preintegrate_thumbnail_representation.py.PreIntegrateThumbnails'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate_resources_path.py.IntegrateResourcesPath'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate.py.IntegrateAsset'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate_legacy.py.IntegrateAssetNew'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate_thumbnail.py.IntegrateThumbnails'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate_hero_version.py.IntegrateHeroVersion'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/integrate_inputlinks.py.IntegrateInputLinks'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/modules/ftrack/plugins/publish/integrate_ftrack_instances.py.IntegrateFtrackInstance'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/modules/ftrack/plugins/publish/integrate_ftrack_farm_status.py.IntegrateFtrackFarmStatus'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/modules/ftrack/plugins/publish/integrate_ftrack_component_overwrite.py.IntegrateFtrackComponentOverwrite'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/modules/ftrack/plugins/publish/integrate_ftrack_api.py.IntegrateFtrackApi'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/modules/ftrack/plugins/publish/integrate_ftrack_note.py.IntegrateFtrackNote'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/modules/timers_manager/plugins/publish/start_timer.py.StartTimer'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/cleanup.py.CleanUp'>
2023-05-24 12:26:57:  0: STDOUT: <class '/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.8-nightly.3/openpype/plugins/publish/cleanup_explicit.py.ExplicitCleanUp'>
2023-05-24 12:26:57:  0: STDOUT: nothing to repeat at position 0
2023-05-24 12:26:58:  0: INFO: Process exit code: 1
2023-05-24 12:26:58:  0: Done executing plugin command of type 'Render Task'
```

**Comment by ClementHector** [comment]
This problem solve by updating click library to version min 8.0.0

**Comment by ClementHector** [comment]
PR => https://github.com/ynput/OpenPype/pull/5065

**Comment by ClementHector** [comment]
PR => https://github.com/ynput/OpenPype/pull/5065
