### ISSUE TITLE
Bug: BuildWorkFile is not getting animation from linked shot / context shot

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#485]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

olivier.osotimehin@fixstudio.com

### Version

3.15.11

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

We want to load linked asset animation that are published in animation or layout stage in the lighting shot . But it doesn't work 
![image](https://github.com/quadproduction/OpenPype/assets/59604835/35036877-af91-424e-8fe9-9d670940ed51)

when i try to load all animation published :
![image](https://github.com/quadproduction/OpenPype/assets/59604835/73cf1438-8069-4328-a1fb-475ff30efe89)

 it doesn't work either, i get only one subset instead of three :
![image](https://github.com/quadproduction/OpenPype/assets/59604835/2828f1cc-8c17-4b37-8d07-f7d137fcedb9)

![image](https://github.com/quadproduction/OpenPype/assets/59604835/7866ed9e-2415-4fe9-805e-86303857ead8)

### Expected Behavior:

get correct subset of asset that are linked and publish when it's in linked mode or all subset that are publish when it's in context mode  

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

TEST_OP2_PUB_23_7 / 001_0020 / light

### Steps To Reproduce:

build workfile from template 

### Relevant log output:

```shell
# # >>> [ Loading setdressMain from enviroTest with loader ReferenceLoader
Loader arguments used :  ] 
# openpype.pipeline.load.utils : Running 'ReferenceLoader' on 'enviroTest'
# SubsetLoader : {'group_name': 'enviroTest_setdressMain_01:asset'}
# File read in  0.066 seconds.
# # *** WRN: >>> { <openpype.hosts.maya.api.workfile_template_builder.MayaTemplateBuilder object at 0x14f087ce33a0> }: [ Failed to process placeholder |root|grp_sets|Linked_setdress_asset with plugin MayaPlaceholderLoadPlugin ] 
# ==============================
# Not enough objects or values.
# 
# ==============================
# Traceback (most recent call last):
#   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.11/openpype/pipeline/workfile/workfile_template_builder.py", line 677, in populate_scene_placeholders
#     placeholder_plugin.populate_placeholder(placeholder)
#   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.11/openpype/hosts/maya/api/workfile_template_builder.py", line 237, in populate_placeholder
#     self.populate_load_placeholder(placeholder)
#   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.11/openpype/pipeline/workfile/workfile_template_builder.py", line 1566, in populate_load_placeholder
#     self.load_succeed(placeholder, container)
#   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.11/openpype/hosts/maya/api/workfile_template_builder.py", line 256, in load_succeed
#     self._parent_in_hierarchy(placeholder, container)
#   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.11/openpype/hosts/maya/api/workfile_template_builder.py", line 291, in _parent_in_hierarchy
#     cmds.reorder(node, front=True)
# RuntimeError: Not enough objects or values.

# >>> [ There's no representation for this placeholder: |root|grp_anims|Linked_animation_asset ] 
# >>> [ There's no representation for this placeholder: |root|grp_cam|Context_camera_asset ] 
# Warning: ???????~???????????
```

**Comment by OlivierOsotimehin** [comment]
fyi the current asset mode work on  3.15.12-quad.0.2
but the linked asset doesnt.

**Comment by OlivierOsotimehin** [comment]
This is a low priority issue

**Comment by SherineKB** [comment]
@OlivierOsotimehin 
I think you have to load the animations from the Current assets instead of the linked assets because the animations are in the shot.

**Comment by OlivierOsotimehin** [comment]
Yes i know but to put it in another way, i would liké to filter all the animation publish and keep only the asset linked to the shot

**Comment by OlivierOsotimehin** [comment]
Again this is low priority

**Comment by SherineKB** [comment]
This ticket is above my knowledge so I leave it to an experimented developer.
