### ISSUE TITLE
Bug: Publish of maya render failed 

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#490]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

olivier.osotimehin@fixstudio.com

### Version

3.15.11

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

At the publish stage of a render there is an error 
You can see the log of the job here  
jobid: 64a07545cc74cd062892d0ca 64a07545cc74cd062892d0c9

I can find this in the log :   File "/users_roaming/chector/Documents/src/OpenPype/.venv/lib/python3.9/site-packages/six.py", line 718, in reraise
that's not suppose to be here i guess : ]

### Expected Behavior:

Publish that ends well with movie review in ftrack 

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

TEST_OP2_PUB_23_7 / cube / shading

### Steps To Reproduce:

publish the workfile to launch the render. The render will failed

### Relevant log output:

```shell
STDOUT: ERROR - Traceback (most recent call last):
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/plugins/publish/integrate.py", line 185, in process
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/plugins/publish/integrate.py", line 318, in register
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/lib/file_transaction.py", line 98, in add
2023-07-01 20:53:40:  0: STDOUT:     raise DuplicateDestinationError(
2023-07-01 20:53:40:  0: STDOUT: openpype.lib.file_transaction.DuplicateDestinationError: Transfer to destination is already in queue: /prod/project/TEST_OP2_PUB_23_7/5_FILM/Assets/cube/work/surface/renders/maya/cube_workfileSurface_v121/Main/cube_workfileSurface_v121_Main_ACEScg.0101.exr -> /prod/project/TEST_OP2_PUB_23_7/5_FILM/Assets/cube/publish/render/renderSurfaceMain_beauty/v056/cube_surf_renderSurfaceMain_beauty_ACEScg_v056.0101.exr. It's not allowed to be replaced by a new transfer from /tmp/op_transcoding_bdi1cb76/cube_workfileSurface_v121_Main_ACEScg.0101.exr
2023-07-01 20:53:40:  0: STDOUT: During handling of the above exception, another exception occurred:
2023-07-01 20:53:40:  0: STDOUT: Traceback (most recent call last):
2023-07-01 20:53:40:  0: STDOUT:   File "/prod/softprod/apps/openpype/LINUX/3.15.0/dependencies/pyblish/plugin.py", line 527, in __explicit_process
2023-07-01 20:53:40:  0: STDOUT:     runner(*args)
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/plugins/publish/integrate.py", line 190, in process
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/chector/Documents/src/OpenPype/.venv/lib/python3.9/site-packages/six.py", line 718, in reraise
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/plugins/publish/integrate.py", line 185, in process
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/plugins/publish/integrate.py", line 318, in register
2023-07-01 20:53:40:  0: STDOUT:   File "/users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.12-quad.0.2/openpype/lib/file_transaction.py", line 98, in add
2023-07-01 20:53:40:  0: STDOUT:     raise DuplicateDestinationError(
2023-07-01 20:53:40:  0: STDOUT: openpype.pipeline.publish.publish_plugins.KnownPublishError: Transfer to destination is already in queue: /prod/project/TEST_OP2_PUB_23_7/5_FILM/Assets/cube/work/surface/renders/maya/cube_workfileSurface_v121/Main/cube_workfileSurface_v121_Main_ACEScg.0101.exr -> /prod/project/TEST_OP2_PUB_23_7/5_FILM/Assets/cube/publish/render/renderSurfaceMain_beauty/v056/cube_surf_renderSurfaceMain_beauty_ACEScg_v056.0101.exr. It's not allowed to be replaced by a new transfer from /tmp/op_transcoding_bdi1cb76/cube_workfileSurface_v121_Main_ACEScg.0101.exr
2023-07-01 20:53:40:  0: STDOUT: Traceback (most recent call last):
```

### Additional context:

ı ¢ħænŋ€

**Comment by ccaillot** [comment]
This has been fixed y add the {representation} flag to render publish template
