### ISSUE TITLE
Maya Farm Render Failed

### ISSUE THREAD

**Issue by SherineKB** [quadproduction/OpenPype#494]
**Task:** Model
**Process:** New scene -> Build workfile from template -> Save -> Publish.
**Error:** Render on farm failed 

![Image](https://user-images.githubusercontent.com/130908605/250804353-4776e245-5fe6-4322-bc40-d30feed84432.png)

```
=======================================================
Error
=======================================================
Error: Global job preload script '/tmp/deadline/nodeloc050/plugins/64a3cb75cc74cd062892d18c/GlobalJobPreLoad.py': RuntimeError : Failed to run OpenPype process to extract environments. (FranticX.Scripting.PythonNetException)
  File "/tmp/deadline/nodeloc050/plugins/64a3cb75cc74cd062892d18c/GlobalJobPreLoad.py", line 437, in __main__
    inject_openpype_environment(deadlinePlugin)
  File "/tmp/deadline/nodeloc050/plugins/64a3cb75cc74cd062892d18c/GlobalJobPreLoad.py", line 371, in inject_openpype_environment
    "Failed to run OpenPype process to extract environments."
   at Python.Runtime.PyObject.Invoke(PyObject[] args)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyObject[] args)
   at FranticX.Scripting.PythonNetScriptEngine.CallFunction(String moduleName, String functionName, Object[] args)
   at Deadline.Plugins.PluginWrapper.d()
   at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)

=======================================================
Type
=======================================================
RenderPluginException

=======================================================
```

**Comment by SherineKB** [comment]
It can be linked to this: 
![Image](https://github.com/quadproduction/OpenPype/assets/130908605/4a046c61-8bbd-4b67-8fa7-b1b9e7dd2d7b)

**Comment by ccaillot** [comment]
Since this [PR](https://github.com/ynput/OpenPype/pull/5244), this issue can happen.

Still under investigation...

**Comment by ClementHector** [comment]
The last log line of the job sais:
```2023-07-06 15:47:46:  0: '/users_roaming/skacmazbelhaine/Thinkbox/Deadline10/pythonAPIs/8V8myYiuCTeqVADSSX273A==' already exists. Skipping extraction of PythonSync.```
it seem to be a specific problem of sherine profile.
