### ISSUE TITLE
Enhancement: add substance painter to the openpype software

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#507]
### Is there an existing issue for this?

- I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

we would like to add substance painter to the avalaible software 

### How would you imagine the implementation of the feature?

there is normaly a first implementation done by bigroy that's avalaible.

### Are there any labels you wish to add?

- I have added the relevant labels to the enhancement request.

**Comment by ClementHector** [comment]
I have this error when i  open subtance on project `TEST_OP2_PUV_23_7` with production software:

```python
WARNING:openpype.tools.launcher.window.LauncherWindow:Action launch failed.
Traceback (most recent call last):
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/tools/launcher/window.py", line 411, in run_action
    action().process(filtered_session)
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/tools/launcher/actions.py", line 112, in process
    self.application.launch(
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/lib/applications.py", line 363, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/lib/applications.py", line 516, in launch
    return context.launch()
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/lib/applications.py", line 1237, in launch
    prelaunch_hook.execute()
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hooks/pre_ocio_hook.py", line 37, in execute
    config_data = get_imageio_config(
  File "/users_roaming/chector/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/pipeline/colorspace.py", line 420, in get_imageio_config
    raise FileExistsError(
FileExistsError: No OCIO config found in settings. It is either missing or there is typo in path inputs
```

To see the error:
1. open terminal
2. enter `env OPENPYPE_MONGO=mongodb://dockerquad:27027 /prod/softprod/apps/openpype/LINUX/3.15.0/openpype_console`
3. open project  `TEST_OP2_PUV_23_7`
4. open a task with substance

**Comment by SherineKB** [comment]
I disabled this and it's now working.
![Image](https://github.com/quadproduction/OpenPype/assets/130908605/d06ec305-1403-4bab-8d67-adba7413ad85)
