### ISSUE TITLE
Bug: error publish camera instance

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#527]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

olivier.osotimehin@fixstudio.com

### Version

3.15.12-quad.3.0

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

Publish of camera error
openpype complain that the camera is in a hierarchy and that .ma is // pyblish.ExtractColorspaceData : Extension 'ma' is not in allowed extensions.

### Expected Behavior:

publish of camera good

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

SILKIES_FR3_S03_23_20 / Shots / 004_0010 / Layout

### Steps To Reproduce:

publish just the item cameraBasic

### Relevant log output:

```shell
b'Processing Camera (Alembic)'
# WARNING - Camera hierarchy contains additional geometry. Extraction will fail.
// Warning: pyblish.ExtractCameraAlembic : Camera hierarchy contains additional geometry. Extraction will fail.
# # ERROR - Traceback (most recent call last):
#   File "/prod/softprod/apps/openpype/LINUX/3.15.0/dependencies/pyblish/plugin.py", line 527, in __explicit_process
#     runner(*args)
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/plugins/publish/extract_camera_alembic.py", line 102, in process
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/plugins/publish/extract_camera_alembic.py", line 2, in AbcExport
# RuntimeError: |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have parenting relationships
# |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have an ancestor relationship.
# 
# Traceback (most recent call last):
#   File "/prod/softprod/apps/openpype/LINUX/3.15.0/dependencies/pyblish/plugin.py", line 527, in __explicit_process
#     runner(*args)
#   File "<string>", line 102, in process
#   File "<string>", line 2, in AbcExport
# RuntimeError: |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have parenting relationships
# |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have an ancestor relationship.

// Error: pyblish.plugin : Traceback (most recent call last):
//   File "/prod/softprod/apps/openpype/LINUX/3.15.0/dependencies/pyblish/plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/plugins/publish/extract_camera_alembic.py", line 102, in process
//   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/plugins/publish/extract_camera_alembic.py", line 2, in AbcExport
// RuntimeError: |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have parenting relationships
// |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have an ancestor relationship.
// 
// Traceback (most recent call last):
//   File "/prod/softprod/apps/openpype/LINUX/3.15.0/dependencies/pyblish/plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "<string>", line 102, in process
//   File "<string>", line 2, in AbcExport
// RuntimeError: |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have parenting relationships
// |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have an ancestor relationship.
b'Processing Camera (Maya Scene)'
# INFO - Looking in settings for scene type ...
// pyblish.ExtractCameraMayaScene : Looking in settings for scene type ...
# INFO - Using ma as scene type
// pyblish.ExtractCameraMayaScene : Using ma as scene type
# INFO - Performing camera bakes: ['|root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera']
// pyblish.ExtractCameraMayaScene : Performing camera bakes: ['|root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera']
# INFO - Performing extraction..
// pyblish.ExtractCameraMayaScene : Performing extraction..
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
// Error: Connection not made: 'camera_camerarigMain_01:vertical_gate_parentConstraint1.constraintTranslateX' -> 'camera_camerarigMain_01:full_gate.translateX'.  Destination is locked.
# INFO - Extracted instance 'cameraBasic' to: /usr/tmp/pyblish_tmp_ghpm63vz/cameraBasic.ma
// pyblish.ExtractCameraMayaScene : Extracted instance 'cameraBasic' to: /usr/tmp/pyblish_tmp_ghpm63vz/cameraBasic.ma
b'Processing Transcode color spaces'
# DEBUG - Looking for matching profile for: hosts: "maya" | families: "camera" | task_names: "layout" | task_types: "layout" | subsets: "cameraBasic"
// pyblish.ExtractOIIOTranscode : Looking for matching profile for: hosts: "maya" | families: "camera" | task_names: "layout" | task_types: "layout" | subsets: "cameraBasic"
# DEBUG - Profile selected: {'families': [], 'hosts': ['maya'], 'task_types': [], 'task_names': [], 'subsets': [], 'delete_original': True, 'outputs': {'movie': {'extension': '', 'transcoding_type': 'display', 'colorspace': 'ACES - ACEScg', 'display': 'ACES', 'view': 'sRGB', 'oiiotool_args': {'additional_command_args': []}, 'tags': ['review', 'ftrackreview'], 'custom_tags': []}}}
// pyblish.ExtractOIIOTranscode : Profile selected: {'families': [], 'hosts': ['maya'], 'task_types': [], 'task_names': [], 'subsets': [], 'delete_original': True, 'outputs': {'movie': {'extension': '', 'transcoding_type': 'display', 'colorspace': 'ACES - ACEScg', 'display': 'ACES', 'view': 'sRGB', 'oiiotool_args': {'additional_command_args': []}, 'tags': ['review', 'ftrackreview'], 'custom_tags': []}}}
# DEBUG - profile: {'families': [], 'hosts': ['maya'], 'task_types': [], 'task_names': [], 'subsets': [], 'delete_original': True, 'outputs': {'movie': {'extension': '', 'transcoding_type': 'display', 'colorspace': 'ACES - ACEScg', 'display': 'ACES', 'view': 'sRGB', 'oiiotool_args': {'additional_command_args': []}, 'tags': ['review', 'ftrackreview'], 'custom_tags': []}}}
// pyblish.ExtractOIIOTranscode : profile: {'families': [], 'hosts': ['maya'], 'task_types': [], 'task_names': [], 'subsets': [], 'delete_original': True, 'outputs': {'movie': {'extension': '', 'transcoding_type': 'display', 'colorspace': 'ACES - ACEScg', 'display': 'ACES', 'view': 'sRGB', 'oiiotool_args': {'additional_command_args': []}, 'tags': ['review', 'ftrackreview'], 'custom_tags': []}}}
# DEBUG - repre (1): `ma`
// pyblish.ExtractOIIOTranscode : repre (1): `ma`
# DEBUG - Representation 'ma' has unsupported extension: 'ma'. Skipped.
// pyblish.ExtractOIIOTranscode : Representation 'ma' has unsupported extension: 'ma'. Skipped.
b'Processing Extract Colorspace data'
# DEBUG - __ ext: `ma`
// pyblish.ExtractColorspaceData : __ ext: `ma`
# DEBUG - Extension 'ma' is not in allowed extensions.
// pyblish.ExtractColorspaceData : Extension 'ma' is not in allowed extensions.
```

**Comment by OlivierOsotimehin** [comment]
i have to recreate the settings that make it behave like that ... don't remember them have to search. can be put on hold
