### ISSUE TITLE
Displacement Arnold not saved when publishing

### ISSUE THREAD

**Issue by louparis** [quadproduction/OpenPype#552]

**Comment by louparis** [comment]
@MarcGutmann to be tested

**Comment by OlivierOsotimehin** [comment]
I should add that from a workflow point of view the look of the object is defined by the material and subdivision settings and primary visibility, specular visibility,etc, all attributs that are carried by the shape. 
For exemple for displace, it's in the surfacing stage that's done, and you set your iterations, height, zero level settings accordingly

**Comment by OlivierOsotimehin** [comment]
we can find in the .json look file generated by openpye  already the settings needed : 
"attributes": {"aiSubdivType": "catclark", "aiDispPadding": 3.0}}, etc etc 

/prod/project/VAILLANT_23_30/5_FILM/Assets/hare/publish/look/lookBasic/hero/hare_lookBasic_hero.json

**Comment by OlivierOsotimehin** [comment]
when i test to load a look on an animation asset "hare" 
you can load it in the shot **800_0010** project **VAILLANT_23_30**  (i exported an animation of hare)
i load the look and i have this log : 
// openpype.hosts.maya.api.lib : Reusing loaded look ..
# Traceback (most recent call last):
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/tools/mayalookassigner/app.py", line 280, in on_process_selected
#     assign_look_by_version(nodes, version_id=version["_id"])
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/api/lib.py", line 1662, in assign_look_by_version
#     apply_shaders(relationships, shader_nodes, nodes)
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/api/lib.py", line 1803, in apply_shaders
#     apply_attributes(attributes, nodes_by_id)
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/api/lib.py", line 1550, in apply_attributes
#     set_attribute(attr, value, node)
#   File "/users_roaming/oso/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/hosts/maya/api/lib.py", line 1527, in set_attribute
#     cmds.setAttr(node_attr, value, type=attr_type)
# RuntimeError: setAttr: The attribute '_800_0010_hare_rigBasic_01_animation_01:body_GeoShapeDeformed.aiSubdivType' does not accept data of type 'string'.
# 

so there is some data type error

**Comment by OlivierOsotimehin** [comment]
to sum up : this was possible before with publish of look in openpype, there is now a bug that prevent the data exported to be applied when we apply the look. Should be a quick fix
